name: Bug Report
description: Report a bug you found in the project
title: "[BUG] - Short description of the issue"
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following template to help us better understand the issue.

  - type: input
    attributes:
      label: "What happened?"
      description: "Describe what happened when you encountered the bug."
      placeholder: "Enter the error message or describe the issue."
      required: true

  - type: input
    attributes:
      label: "Steps to Reproduce"
      description: "Provide a list of steps to reproduce the bug."
      placeholder: "Step 1, Step 2, etc."
      required: true

  - type: input
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe the expected result."
      required: true

  - type: input
    attributes:
      label: "Screenshots or Logs"
      description: "If applicable, add screenshots or logs to help explain your problem."
      placeholder: "Include relevant files."
      required: false
