name: CI/CD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 


  # Job 3: Frontend - Build and Test Angular Application
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 20.19.0
        uses: actions/setup-node@v2
        with:
          node-version: '20.19.0'

      - name: Install Angular dependencies
        run: npm install --prefix Front

      - name: Build Angular production
        run: npm run build --prefix Front --prod
