name: Simple CI Workflow for Event Management App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Backend - Build and Test Spring Boot Application
  backend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (Spring Boot)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'        # Set Java version to 17
          distribution: 'zulu' # See 'Supported distributions' for available options


      # Step 3: Build and test Spring Boot backend using Maven
      - name: Build and test Spring Boot backend
        run: mvn clean install -f Back/pom.xml

  # Job 2: Frontend - Build and Test Angular Application
  frontend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js 20.19.0 (Angular)
      - name: Set up Node.js 20.19.0
        uses: actions/setup-node@v2
        with:
          node-version: '20.19.0'

      # Step 3: Install Angular dependencies
      - name: Install Angular dependencies
        run: npm install --prefix Front

      # Step 5: Build Angular application for production
      - name: Build Angular production
        run: npm run build --prefix Front --prod
